
toplevel: from-github/pseudocap/atlas_conf_2017_028
workflow: workflow.yml
outputs: fit/limits.txt,selection/hist-testrun.root
pars:
  cxaodfile: 'root://eosatlas.cern.ch///eos/atlas/atlascerngroupdisk/phys-exotics/CxAOD/CxAOD_26/HIGG5D1_13TeV/CxAOD_00-26-01/monoHbb/group.phys-exotics.mc15_13TeV.304123.MGPy8EG_A14NNPDF23LO_zp2hdm_bb_mzp1400_mA600.s2608.HIGG5D1.26-01_CxAOD.root/group.phys-exotics.9826844._000001.CxAOD.root'
  did: 304123
  xsec_pb: '1.0'
  k_factor: '1.0'
  filt_eff: '1.0'
  mctype: MadGraphPythia8

