stages:
  - name: selection
    dependencies: ['init']
    scheduler:
      scheduler_type: singlestep-stage
      parameters:
        cxaodfile: {stages: init, output: cxaodfile, unwrap: true}
        did:       {stages: init, output: did, unwrap: true}
        xsec_pb:   {stages: init, output: xsec_pb, unwrap: true}
        k_factor:  {stages: init, output: k_factor, unwrap: true}
        filt_eff:  {stages: init, output: filt_eff, unwrap: true}
        nametag: 'recast'
        mctype: {stages: init, output: mctype, unwrap: true}
        outputdir: '{workdir}/output'
      step: {$ref: 'selscript.yml#'}
  - name: fit
    dependencies: ['selection']
    scheduler:
      scheduler_type: singlestep-stage
      parameters:
        fitinputdir: '{workdir}/fitinputs'
        signalfile: {stages: selection, output: out, unwrap: true}
        zerolepbkg: 'root://eosuser.cern.ch///eos/project/r/recast/atlas/atlas_conf_2017_028/v22l/LimitHistograms.MonoH.vvbb.13TeV.MunichMPI.v22l_unblinded.qcdIncluded.bkgOnly.root'
        onelepbkg: 'root://eosuser.cern.ch///eos/project/r/recast/atlas/atlas_conf_2017_028/v22l/LimitHistograms.MonoH.lvbb.13TeV.MunichMPI.v22l.root'
        twolepbkg: 'root://eosuser.cern.ch///eos/project/r/recast/atlas/atlas_conf_2017_028/v22l/LimitHistograms.MonoH.llbb.13TeV.MunichMPI.v22l.root'
        nametag: 'recast'
        limitfile: '{workdir}/limits.txt'
      step: {$ref: 'fitscript.yml#'}
