stages:
  - name: 'iteration_0'
    dependencies: []
    scheduler:
      scheduler_type: singlestep-stage
      parameters:
        first: first
      workflow: {$ref: 'oracle_flow.yml'}

  - name: 'iteration_0'
    dependencies: []
    scheduler:
      scheduler_type: singlestep-stage
      parameters:
        first: first
      workflow: {$ref: 'oracle_flow.yml'}

  - name: 'iteration_1'
    dependencies: [iteration_0]
    scheduler:
      scheduler_type: singlestep-stage
      parameters:
        first: {stages: 'iteration_0[*].evaluate_oracle', output: outputA, unwrap: true}
      workflow: {$ref: 'oracle_flow.yml'}
