stages:
  - name: 'subStage'
    dependencies: [init]
    scheduler:
      scheduler_type: singlestep-stage
      parameters:
        subpar: {stages: init, output: subpar, unwrap: true}
      step: {$ref: 'substeps.yml#/subStep'}




#