stages:
  - name: parallel
    dependencies: ['init']
    scheduler:
      scheduler_type: multistep-stage
      workflow: {$ref: 'straight_prod.yml'}
      parameters:
        proc_card: {stages: init, output: proc_card, unwrap: true}
        param_card: {stages: init, output: param_card, unwrap: true}
        nevents: {stages: init, output: nevents, unwrap: true}
        DSID: {stages: init, output: DSID, unwrap: true}
        generate_seed: {stages: init, output: generate_seed, unwrap: true}
        simulation_seed: {stages: init, output: simulation_seed, unwrap: true}
      scatter:
        parameters: [generate_seed,simulation_seed]
        method: zip
  - name: merge
    dependencies: [parallel]
    scheduler:
      scheduler_type: singlestep-stage
      parameters:
        mergedfile: '{workdir}/merged.root'
        rootfiles: {stages: 'parallel.[*].derivation', output: daodfile}
      step: {$ref: 'rootsteps.yml#/root_merge'}
